version: 2.1

orbs:
  win: circleci/windows@5.0
  node: circleci/node@5.1.0

jobs:
  windows:
    executor: win/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '21.1.0'
      - run: node --version
      - run: yarn
      - run: yarn build

workflows:
  windows:
    jobs:
      - windows
