version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  windows:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Install NVM
          command: choco install nvm -y
      - run:
          shell: bash.exe
          command: |
            nvm list
            nvm install 18.18.2
            nvm use 18.18.2
      - run: node --version
      - run: npm install -g yarn
      - run: yarn
      - run: yarn build

workflows:
  windows:
    jobs:
      - windows