# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  win: circleci/windows@5.0

jobs:
  test-windows:
    executor: win/default
    steps:
      - checkout
      # - run: choco install nodejs --yes
      - run: node --version
      - run: |
          cd ..
          git clone https://github.com/oclif/core.git --branch mdonnalley/char-aliases
      - run: |
          cd core
          yarn
          yarn build
      - run: yarn test:e2e


# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-windows: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test-windows
